### ISSUE TITLE
This repo is actually epic?!

### ISSUE THREAD

**Issue by Decimation** [BergEB/proto-bengt#1]
Wow, Bengt! I am so proud of you. I guess we were right all along - the **addy really does go hard!** However, I noticed the absence of my name in the Acknowledgements section of your readme. Sad! 

Based & Bengtpilled.

Shut it down!

**Comment by Decimation** [comment]
Actually, some of the code needs to be improved. Fix your naming conventions. Sad!

**DATA!**

**Comment by BergEB** [comment]
Ok bro, thanks! I will try to use naming conventions that are more straightforward and meaningful.

_Addy goes hard_
