### ISSUE TITLE
Unsatisfactory forsaken adolescence

### ISSUE THREAD

**Issue by Decimation** [BergEB/proto-bengt#2]
Baaaaad fuckin youth

- Profile Pic - 

No Vacation - Summer Break Mixtape

★˛˚˛*˛°.˛*.˛°˛.*★˚˛*˛°.˛*.˛°˛.*★*★* 。*˛.
˛°_██_*.。*./ ♥ \ .˛* .˛。.˛.*.★* *★ 。*
˛. (´• ̮•)*.。*/♫.♫\*˛.* ˛_Π_____.♥ ♥ ˛* ˛*
.°( . • . ) ˛°./• '♫ ' •\.˛*./______/~＼*. ˛*.。˛* ˛.*。
*(...'•'.. ) *˛╬╬╬╬╬˛°.｜田田 ｜門｜╬╬╬╬╬*˚ .˛ 
С наступающим!!!

**Comment by BergEB** [comment]
how creative!

_Addy goes hard_
